backend:
  #name: github
  #repo: thomas6791/bernardcook
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: nav
        file: "_data/navigation.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: navigationItems
            widget: list
            fields:
              - {label: "Display Text", name: displayText, widget: string}
              - {label: URL, name: url, widget: string}
              - label: "Item Type"
                name: itemType
                widget: select
                options: ["Link", "Button"]

  - name: "reviews"
    label: "Avis clients"
    folder: "_reviews"
    create: true
    fields:
      - {label: "Nom du client", name: "author", widget: "string" }
      - {label: "Note de l'avis", name: "note", widget: "number", default: 5, value_type: "int", min: 1, max: 5, step: 1 }
      - {label: "Contenu texte", name: "body", widget: "markdown"}

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page de test'
        name: 'test'
        file: 'test.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Titre', name: 'titre', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}
      - label: 'Page Isolation extérieure'
        name: 'isolation extétérieure'
        file: 'isolation.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Titre', name: 'titre', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}

  - label: "Autres suggestions - Plats"
    name: "plats"
    folder: "_plats/"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: 'Titre du plat', name: 'title', widget: 'string' }
      - {label: "Activé/En ligne", name: "published", widget: "boolean", default: true}
      - {label: 'Image du plat', name: 'image', widget: "image", required: true}
      - {label: "Contenu texte", name: "body", widget: "markdown"}
