backend:
  #name: github
  #repo: thomas6791/bernardcook
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page Isolation extérieure'
        name: 'isolation extétérieure'
        file: 'isolation.md'
        fields:
          - { label: 'Titre', name: 'titre', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}
      - label: 'Page Ravalement de façade'
        name: 'ravalement façade'
        file: 'ravalement.md'
        fields:
          - { label: 'Titre', name: 'titre', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}
      - label: 'Page Travaux de toiture'
        name: 'toiture'
        file: 'toiture.md'
        fields:
          - { label: 'Titre', name: 'titre', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown'}

  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Texte", name: "body", widget: "markdown"}

  - name: "reviews"
    label: "Avis clients"
    folder: "_reviews"
    create: true
    fields:
      - {label: "Nom du client", name: "author", widget: "string" }
      - {label: "Note de l'avis", name: "note", widget: "number", default: 5, value_type: "int", min: 1, max: 5, step: 1 }
      - {label: "Contenu texte", name: "body", widget: "markdown"}

